RentalApp/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('users/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    
    path('tenants/', include(('tenants.urls', 'Tenant'), namespace='Tenant')),
    path('properties/', include('properties.urls', namespace='Properties')),
    path('contracts/', include('contracts.urls', namespace='Contracts')),
    path('payments/', include('payments.urls', namespace='Payments')),

    
]

accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.register_user, name='register'),
    path('complete-profile/', views.complete_owner_profile, name='complete_owner_profile'),
    path('settings/', views.settings_view_page, name='settings'),
    
    path('password_reset_local/', views.password_reset_local, name='password_reset_local'),
    path('password_reset_complete/', views.password_reset_complete_local, name='password_reset_complete'),


    path('password_reset/',
            auth_views.PasswordResetView.as_view(
                template_name = 'registration/password_reset_form.html',
                email_template_name = 'registration/password_reset_email.html',
                subject_template_name = 'registration/password_reset_subject.txt',
                success_url = '/password_reset/done/',
            ),
            name ='password_reset'
        ),

    path('password_reset/done/',
            auth_views.PasswordResetDoneView.as_view(
                template_name= 'registration/password_reset_done.html'
            ),
            name='password_reset_done'
        ),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='registration/password_reset_confirm.html'
    ), name='password_reset_confirm'),
    
    path('reset/done/',
            auth_views.PasswordResetCompleteView.as_view(
                template_name='registration/password_reset_complete.html'
            ),
            name = 'password_reset_complete'
        ),
]

contracts/urls.py
from django.urls import path
from . import views

app_name = 'Contracts'

urlpatterns = [
    path('', views.contract_list, name='contract_list'),
    path('add/', views.contract_create, name='contract_create'),
    path('edit/<int:pk>/', views.contract_update, name='contract_update'),
    path('delete/<int:pk>/', views.contract_delete, name='contract_delete'),

    path('pdf/<int:pk>/', views.generate_contract_pdf, name='generate_contract_pdf'),
]

core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.home, name='home'),
]

payments/urls.py
from django.urls import path
from . import views

app_name = 'Payments'

urlpatterns = [
    path('', views.payment_list, name='payment_list'),
    path('add/', views.payment_create, name='payment_create'),
    path('edit/<int:pk>/', views.payment_update, name='payment_update'),
    path('delete/<int:pk>/', views.payment_delete, name='payment_delete'),
    path('<int:pk>/recibo/', views.generate_payment_receipt_pdf, name='generate_payment_receipt_pdf'),

]

tenants/urls.py
from django.urls import path
from . import views

app_name = 'Tenant'

urlpatterns = [
    path('', views.tenant_list, name='tenant_list'),
    path('add/', views.tenant_create, name='tenant_form'),
    path('edit/<int:pk>/', views.tenant_update, name='tenant_update'),
    path('delete/<int:pk>/', views.tenant_delete, name='tenant_delete'),

    path('ajax/tenant-list-ajax/',views.tenant_list_ajax,name='tenant_list_ajax'),
]

templates/base.html
{# RentalApp/templates/base.html #}
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}Sistema de Gerenciamento de Aluguéis{% endblock %}</title>
    <link href="https://fonts.googleapis.com/css2?family=Ancizar+Sans:ital,wght@0,100..1000;1,100..1000&family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" /> 
    <link rel="stylesheet" href="{% static 'css/style.css' %}?v=1.0.1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link rel="icon" type="image/x-icon" href="{% static 'logo.ico' %}">

</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top navbar-3d">
        <div class="container-fluid">
            <a class="navbar-brand ms-3" href="{% url 'core:home' %}">Meus Aluguéis</a>
            
    <button class="navbar-toggler " type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
        <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
        <ul class="navbar-nav align-items-center">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'Tenant:tenant_list' %}">Inquilinos</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'Properties:property_list' %}">Imóveis</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'Contracts:contract_list' %}">Contratos</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'Payments:payment_list' %}">Pagamentos</a>
            </li>

            {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:settings' %}">Configurações</a> 
            </li>
                <li class="nav-item">
            <form action="{% url 'logout' %}" method="post" style="display: inline;">
                {% csrf_token %}
                <button type="submit" class="btn btn-outline-light btn-sm btn-sair">Sair</button>
            </form>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'login' %}">Entrar</a>
            </li>
            {% endif %}
        </ul>
        </div>
    </div>
</nav>
    <div class="container mt-4"> 
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endfor %}
        {% endif %}

        {% block content %}
        {% endblock %}

    </div>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>
<script src="{% static 'javascript/app.js' %}?v=1.0.3"></script>